.TH CALCLEANER 1 2022-08-03 "Calendar Cleaner {VERSION}" "General Commands Manual"


.SH NAME

calclaner \- purge old events from CalDAV calendars


.SH SYNOPSIS

.B calcleaner
.RI [ -h ]
.RI [ -v ]


.SH DESCRIPTION

CalCleaner is a simple utility to purge old events from CalDAV calendars.

.SH OPTIONS

.TP
\fB-h\fR, \fB--help\fR
show the help message and exit

.TP
\fB-v\fR, \fB--version\fR
show program's version number and exit

.SH WEB SITE

https://github.com/flozz/calcleaner/


.SH REPORTING BUGS

Report bugs to <https://github.com/flozz/calcleaner/issues>.


.SH COPYRIGHT

Copyright © 2022 Fabien Loison

CalCleaner is free software under GNU GPL v3+ licence
<http://gnu.org/licenses/gpl.html>, you are free to modify and redistribute it
under the terms of the license.
